#!/bin/bash
set -euo pipefail

path=/growroot
udevadm settle

#Following function takes name as argument e.g. coreos.inst.install_dev and finds its value from
#cmdline (which is passed at boot time)
cmdline=( $(</proc/cmdline) )
karg() {
    local name="$1" value=""
    for arg in "${cmdline[@]}"; do
        if [[ "${arg%%=*}" == "${name}" ]]; then
            value="${arg#*=}"
        fi
    done
    echo "${value}"
}

# Get installation device
installation_device="$(karg coreos.inst.install_dev)"
if [ "${installation_device##*/}" = "${installation_device}" ]; then
    # karg contains no slashes.  Prepend "/dev/" for compatibility.
    installation_device="/dev/${installation_device}"
fi

#Get number of partitions avaiable for the installation_device and choose last 
#partition to grow till available disk size.
device=${installation_device##*/}
last_partition="$(ls /sys/block/${device}/*/partition | wc -l)"
growpart $installation_device $last_partition
echo "growpart executed on "$installation_device" "$last_partition" "

crypt=$(lsblk -ln -o NAME,TYPE | grep crypt | awk '{print $1}')
if [[ -z ${crypt} ]]; then
    exit 1
fi
cryptsetup resize ${crypt}
lvm pvresize /dev/mapper/${crypt}

lvm vgchange -ay rootvg

# if running on Fedora, resize rootlv and fs to fill the disk
if [ ! -z "$(grep "ID=fedora" /etc/os-release )" ]; then
        echo "Expanding /dev/rootvg/rootlv to use all free space."
        lvm lvextend -l +100%FREE /dev/rootvg/rootlv
        echo "Running e2fsck on /dev/rootvg/rootlv"
        e2fsck -f -y /dev/rootvg/rootlv < /dev/null
        echo "Resizing filesystem on /dev/rootvg/rootlv."
        resize2fs /dev/rootvg/rootlv
fi

if [[ ! -e /dev/disk/by-label/root ]]; then
    dm=$(blkid --label root)
    if [[ -z ${dm} ]]; then
        exit 1
    fi
    ln -s ${dm} /dev/disk/by-label/root
fi

mkdir -p ${path}
