#!/bin/bash

set -e

# this has to come from /proc/cmdline at least... or configured somewhere before provisioning
MANUFACTURING_SERVICE_URL="http://fdo-test.puiterwijk.org:8080" DIUN_PUB_KEY_INSECURE="true" /usr/bin/fdo-manufacturing-client

mkdir -p /bootmount
TYPE=$(lsblk --output FSTYPE /dev/disk/by-label/boot | tail -n1)
mount -t ${TYPE} /dev/disk/by-label/boot /bootmount

cp -a /etc/device-credentials /bootmount/device-credentials